services:

  postgresql:
    image: postgres:latest
    container_name: db
    restart: always
    env_file:
      - .env
    ports:
      - '5433:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - espaco
    
  pgadmin:
    container_name: gui_db
    image: dpage/pgadmin4:8.8
    env_file:
      - .env
    ports:
      - '8090:80'
    depends_on:
      - postgresql
    networks:
      - espaco
  
  newsletter:
    container_name: newsletter_service
    build: 
      context: ./server
    env_file:
      - .env
    ports:
      - 5001:5001 # Newsletter Service
      - 5002:5002 # Weather Service
    depends_on:
      postgresql:
        condition: service_healthy
    networks:
      - espaco

networks:
  espaco:
