services:
  # --------------------- Django Framework Server ------------------
  api_server:
    build:
      context: ./api_server
    env_file:
      - .env
    networks:
      - espaco
    ports:
      - "8000:8000"             ## Porta para aplicação Django
    volumes:
      - ./api_server:./app

  # --------------------- Database Server e GUI ------------------
  postgresql:
    container_name: 'db'
    image: postgres:latest
    ports:
      - "7777:5432"
    networks:
      - espaco
    env_file:
      - .env

  pgadmin:
    container_name: 'gui_db'
    image: dpage/pgadmin4:8.8
    networks:
      - espaco
    ports:
      - "7778:80"
    env_file:
      - .env

  # --------------------- API Gateway ------------------
  nginx:
    container_name: nginx
    build: ./nginx
    volumes:
      - static:/static          ## Revisar: os arquivos .css e .js do Django não estão sendo entregues ao cliente
    ports:
      - "9999:80"
    depends_on:
      - api_server

# --------------------- Rede ------------------
networks:
  espaco:
    driver: bridge      ## Cria uma ponte entre a sua rede local e a do container(espaco).

# --------------------- Volumes ------------------
volumes:
  api_server:

  