# Stack de serviços postgresql + pgadmin4
version: '3.1'
services:

  postgresql:
    container_name: 'db'
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: gatinho_estrelar
    ports:
      - "7777:5432"
  
  pgadmin:
    container_name: 'gui_db'
    image: dpage/pgadmin4:8.8
    environment:
      PGADMIN_DEFAULT_EMAIL: "kae.budke@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "gatinho_estrelar"
    ports:
      - "7778:80"
    depends_on:
      - postgresql