# Generated by Django 5.0.6 on 2024-06-18 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Localizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('nome', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CondicoesClimaticas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('descricao_weather', models.CharField(blank=True, max_length=255, null=True)),
                ('temperatura_atual', models.FloatField(blank=True, null=True)),
                ('temperatura_max', models.FloatField(blank=True, null=True)),
                ('temperatura_min', models.FloatField(blank=True, null=True)),
                ('umidade', models.FloatField(blank=True, null=True)),
                ('velocidade_vento', models.FloatField(blank=True, null=True)),
                ('direcao_vento', models.FloatField(blank=True, null=True)),
                ('rajada_vento', models.FloatField(blank=True, null=True)),
                ('localizacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condicoes_climaticas', to='data.localizacao')),
            ],
        ),
    ]
