# Generated by Django 5.0.6 on 2024-06-19 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id_cidade', models.IntegerField(primary_key=True, serialize=False)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=2)),
                ('pais', models.CharField(max_length=2)),
                ('coord_lat', models.FloatField()),
                ('coord_lon', models.FloatField()),
                ('populacao', models.IntegerField()),
                ('timezone', models.IntegerField()),
                ('nascer_sol', models.IntegerField()),
                ('baixar_sol', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Previsao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora_previsao', models.CharField(max_length=20)),
                ('timestamp_previsao', models.IntegerField()),
                ('condicao', models.CharField(max_length=50)),
                ('descricao_condicao', models.CharField(max_length=100)),
                ('temperatura', models.FloatField()),
                ('max_temp', models.FloatField()),
                ('min_temp', models.FloatField()),
                ('sensacao', models.FloatField()),
                ('umidade', models.IntegerField()),
                ('pressao', models.IntegerField()),
                ('direcao_vento', models.IntegerField()),
                ('velocidade_vento', models.FloatField()),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.cidade')),
            ],
        ),
        migrations.DeleteModel(
            name='CondicoesClimaticas',
        ),
        migrations.DeleteModel(
            name='Localizacao',
        ),
    ]
