services:

  # Servidor Web
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./static:/static
      - ./media:/media
    depends_on:
      - django
    networks:
      - app-network
 
  # Web Server Gateway Interface
  gunicorn:
    build:
      context: .
      dockerfile: ./gunicorn/Dockerfile
    command: gunicorn myapp.wsgi:application -w 4 -b 0.0.0.0:8000
    volumes:
      - ./django:/app
      - ./static:/app/static
      - ./media:/app/media
    depends_on:
      - postgres
    networks:
      - app-network

  # Banco de Dados
  postgres:
    image: postgres:latest
    container_name: PostgreSQL
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: mydatabaseuser
      POSTGRES_PASSWORD: mydatabasepassword
    ports:
      - "5432:5432"
    networks:
      - mynetwork

  # API RESTful
  django:
    build:
      context: .
      dockerfile: ./django/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./django:/app
      - ./static:/app/static
      - ./media:/app/media
    depends_on:
      - postgres
    networks:
      - app-network

# Redes
networks:
  app-network:
    driver: bridge

# Armazenamento
volumes:
  postgres_data: