# Stack de serviços mysql + interface web
services:
  mysql:
    image: mysql:latest
    container_name: mysql_server
    environment:
      MYSQL_ROOT_PASSWORD: sirius
      MYSQL_USER: siriusb
      MYSQL_PASSWORD: sirius
      MYSQL_DATABASE: default_schema
    ports:
      - 3310:3306
  
  phpmyadmin:
    image: phpmyadmin
    container_name: pma_interface
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8183:80
