# Stack de serviços postgresql + pgadmin4
services:

  postgresql:

    container_name: 'db_espacial'
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: 'pass'
      TZ: 'America/Campo_Grande'
    ports:
      - "7777:5432"
    
  
  pgadmin:

    container_name: 'gui_sirius'
    image: dpage/pgadmin4:8.12
    environment:
      PGADMIN_DEFAULT_EMAIL: "kae.budke@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "gatinho_estrelar"
    ports:
      - "7878:80"
    # volumes:
      # - ./config.py:/pgadmin4/config.py  # Monta o arquivo de configuração
    depends_on:
      - postgresql
    
    
