# Stack de serviços postgresql + pgadmin4
services:

  workspace:

    container_name: data_service
    env_file:
      - .env
    build:
      context: ./server/data_service
      dockerfile: Dockerfile
    ports:
      - "7777:7777"       
    volumes:
      - ./server/data_service/app:/app
    depends_on:
      postgresql:
        condition: service_healthy
  
  postgresql:

    container_name: 'db'
    image: postgres:latest
    restart: always
    env_file:
      - .env
    ports:
      - "5433:5432"
  
  pgadmin:

    container_name: 'pgadmin4'
    image: dpage/pgadmin4:8.9
    env_file:
      - .env
    ports:
      - "8090:80"
    depends_on:
      - postgresql