# Use postgres/example user/password credentials
version: '3.1'
services:
  postgresql:
    container_name: 'postgresql'
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ascende.Superius2026
    ports:
      - "5433:5432"
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "kae.budke@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "ascende.Superius2026"
    ports:
      - "8090:80"
    depends_on:
      - postgresql