stages:
  - build
  - test
  - deploy

variables:
  DOCKER_TLS_CERTDIR: ""

build:
  stage: build
  script:
    - docker compose build

test:
  stage: test
  script:
    - echo "✔️ Testes básicos (lint, healthcheck, etc)"

deploy:
  stage: deploy
  script:
    - echo "🚀 Deploy automatizado do ambiente"
    - docker compose up -d
  only:
    - main
