services:
  db:
    image: arm64v8/mysql
    container_name: wordpress_db
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    env_file:
      - ".env"

  wordpress:
    image: wordpress
    container_name: wordpress_app
    restart: always
    ports:
      - "8081:80"
    depends_on:
      - db
    env_file:
      - ".env"
    volumes:
      - wordpress:/var/www/html
volumes:
  db_data:
  wordpress: